### ISSUE TITLE
Support for RTX 3090 by targeting Cuda 11 or newer.

### ISSUE THREAD

**Issue by sirisian** [brendenpetersen/deep-symbolic-optimization#18]
In my previous ticket #17 I just realized that I can't run this project. I've ran other Cuda 11 projects and just assumed I could downgrade and run old projects, but that doesn't appear to be the case. Seems like all Tensorflow 1.14 projects don't run. This might be asking a lot (not sure the number of changes) but could this project be updated to work with the newest Tensorflow and Cuda or at least Cuda 11 compatible versions.

**Comment by outdoteth** [comment]
This would be a great feature.
