### ISSUE TITLE
How to save DSR regression model by pickle?

### ISSUE THREAD

**Issue by DrJihyeonPark** [brendenpetersen/deep-symbolic-optimization#20]
[211103.zip](https://github.com/brendenpetersen/deep-symbolic-optimization/files/7467498/211103.zip)
Hi! I'm Jihyeon Park from South Korea. 
I really impressed your concept and idea. 
Now I'm adapting your code in my data.

Here's a question.
Like other machine learning models, I tried to save the model that finished learning by pickle, but failed.

I read your documents to find information in terms of 'save', but I could not find it.
So, could you tell me how to save the model?
I attach my code and data file.

Thank you.

**Comment by brendenpetersen** [comment]
Hi, thanks for your interest! And sorry for the delay, I didn't see this until now.

May I ask why you want to save your model? Typically the model itself is not useful and we only care about the expressions that are generated.

However, we do have a `save` function you can use like `model.save("my_model")`.
