### ISSUE TITLE
Failed to install 

### ISSUE THREAD

**Issue by thw1021** [brendenpetersen/deep-symbolic-optimization#21]
Dear Brenden Petersen,

Thanks for sharing your work. 

I am trying to use conda to install the core packages. However, an error always happens, and I cannot figure out how to solve it. Could you help me, please?

The steps I did:
1. Create a virtual environment: ``conda create -n dsr python=3.8``
2. Install core packages in the virtual environment: ``conda activate dsr``, and ``pip install -e ./dso[all]``

The error is
![Screenshot from 2021-12-08 09-34-10](https://user-images.githubusercontent.com/17957650/145133691-637550ed-bf2f-4fce-ae4d-abd455356a14.png)

Could you give some suggestions, please?

Best,
Hongwei Tang

**Comment by brendenpetersen** [comment]
Sorry, we had an issue where we accidentally added that file to `.gitignore`! We pushed a hotfix. Please try again.

Also, I'm not sure if `python3.8` will work with DSO, as I'm not sure there's a valid `tensorflow1.14` that works with `python3.8`, but I could be wrong about this!

**Comment by thw1021** [comment]
Thank you. Now it looks good.

BTW, `tensorflow1.14` does not work with `python3.8`. `python=3.7` is OK.
