### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by syrnluo** [brendenpetersen/deep-symbolic-optimization#22]
Hi Brenden,

Thanks for your great work! When I was trying to install the package, I always encountered the error message shown in the Figure. Could you  provide some suggestions on how to solve it? 
<img width="572" alt="Screen Shot 2021-12-09 at 2 27 18 PM" src="https://user-images.githubusercontent.com/37712351/145463695-48c92d49-bd38-4add-bcf6-09787f4f19b1.png">

Thanks,
Jiayi

**Comment by brendenpetersen** [comment]
It looks like you are not issuing the `pip install -e ./dso` command from the correct directory. `./dso` should point to the directory containing `setup.py`. Perhaps you did not `cd` into the repository root (default would be `./deep-symbolic-optimization` if you just cloned).
