### ISSUE TITLE
How to calculate recovery rate?

### ISSUE THREAD

**Issue by thw1021** [brendenpetersen/deep-symbolic-optimization#25]
Dear Petersen,

You define the recovery rate as "exact symbolic equivalence" in [your paper](https://openreview.net/forum?id=m5Qsh0kBQG). I do not understand why some recovery rates are between 0 to 1. For example, in table 1, the rate is 0.35 for Nguyen-7 when using DSR. How do you calculate this value? Intuitively, you will either obtain the exact expression (recovery rate is 1), or fail to obtain the right expression (recovery rate is 0).

**Comment by brendenpetersen** [comment]
The algorithm is stochastic. Recovery is binary for a particular run, but the recovery rate is an average across 100 runs with different seeds.
