### ISSUE TITLE
how to install this library

### ISSUE THREAD

**Issue by liuzd2017** [brendenpetersen/deep-symbolic-optimization#27]
I use this command "pip install -e ./dso[all]" to install this library to my computer, but an error occured. this is the error:

ERROR: ./dso[all] is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with bzr+http, bzr+https, bzr+ssh, bzr+sftp, bzr+ftp, bzr+lp, bzr+file, git+http, git+https, git+ssh, git+git, git+file, hg+file, hg+http, hg+https, hg+ssh, hg+static-http, svn+ssh, svn+http, svn+https, svn+svn, svn+file).

could you help me?

**Comment by brendenpetersen** [comment]
See #22
