### ISSUE TITLE
Might be worth mentioning SRBench results

### ISSUE THREAD

**Issue by sgbaird** [brendenpetersen/deep-symbolic-optimization#28]
https://github.com/cavalab/srbench#benchmarked-methods

**Comment by sgbaird** [comment]
From an initial glance, *DSR seems to do pretty well https://arxiv.org/abs/2107.14351

**Comment by brendenpetersen** [comment]
We updated our repo and now include those results in our README :)

**Comment by tluchko** [comment]
How close is this release to what was used in the benchmark and NeurIPS2022?  For example, I see the linear token but does the code use AI Feynman to create subproblems?

**Comment by brendenpetersen** [comment]
@tluchko Good point, unfortunately we weren't able to include the AIF or LSPT components in this release. Though if you look at the ablations in our paper, it hardly makes a difference once you have enough components. Probably just better off running DSR + GP + LINEAR (which are all included in this release) for longer.
