### ISSUE TITLE
Questions on installation

### ISSUE THREAD

**Issue by Ohay-Angah** [brendenpetersen/deep-symbolic-optimization#31]
I am trying to install this great package on my Linux through Docker but keep running into the error below, which obviously is not an issue of the provided install tutorial but might be resulted from surfing on Docker. After running `pip install -e ./dso`,

 ```
/root/anaconda3/compiler_compat/ld: error: /root/anaconda3/lib/python3.7/site-packages/numpy/core/include: read: Is a directory
    collect2: error: ld returned 1 exit status
    /root/anaconda3/lib/python3.7/site-packages/setuptools/dist.py:516: UserWarning: Normalizing '1.0dev' to '1.0.dev0'
      warnings.warn(tmpl.format(**locals()))
    /root/anaconda3/lib/python3.7/site-packages/setuptools/command/easy_install.py:147: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
      EasyInstallDeprecationWarning,
    /root/anaconda3/lib/python3.7/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      setuptools.SetuptoolsDeprecationWarning,
    error: command '/usr/bin/gcc' failed with exit code 1
```

I post this error here wondering if anyone has the experience to fix the 'read' issue when installing this package in a Docker container

**Comment by brendenpetersen** [comment]
Not sure why Docker might affect this. It looks like you may need to install/update `gcc`? Also looks like you're using an Anaconda Python distribution, which is not something we have tested.

**Comment by Ohay-Angah** [comment]
Just want to update. After installing gcc, I can use this great repo, and it does fit Anaconda Python, too
