### ISSUE TITLE
Error if both n_objects and n_cores_batch are greater than 1

### ISSUE THREAD

**Issue by hwfluid** [brendenpetersen/deep-symbolic-optimization#37]
Dear Brenden K. Petersen,

How to understand `n_objects`? I did some tests to set it `n_objects=3` and it seemed that dso would produce three expressions at the same time. But how to decide which one is better?
https://github.com/brendenpetersen/deep-symbolic-optimization/blob/8724839dab910022e24d03debdf564236683474b/dso/dso/program.py#L219

In addition, when `n_objects` is greater than 1, I found `n_cores_batch` must be 1. Otherwise, it can cause an error (please see the attached log file as well as the configurations). 
[error_log_config.zip](https://github.com/brendenpetersen/deep-symbolic-optimization/files/8729444/error_log_config.zip)

Could you give me some suggestions, please?

**Comment by brendenpetersen** [comment]
Hi, `n_objects` is (intentionally) not configurable via config file. It shouldn't be directly changed in the code, so if you changed `n_objects > 1` directly in the code, it won't work but that's not a bug. `n_objects > 1` has no meaning for the `regression` task. It's largely an experimental feature we are using internally for some different use cases in the `control` task. The network outputs `n_objects` traversals (and the existing priors have been updated to apply to these sub-traversals individually), and it's up to the `Task` to decide what to do with them.

**Comment by hwfluid** [comment]
Thank you for your answer. The `n_objects` seems to be some feature I am looking for. I am trying to use DSO to do a special regression task. I have sent an email to you. Could you have a check, please? (If you do not see the email, it may be put in the junk folder by mistake).

Thank you for your time.
