### ISSUE TITLE
Save the model after each epoch

### ISSUE THREAD

**Issue by chenyuxin1999** [brendenpetersen/deep-symbolic-optimization#39]
Hi, love this amazing repository.
I tried to use this code on my custom data with "const" added in the function_set. However, as you know, adding "const" bring more complexity and it really took a long time. So what can I do to save the model after running every epoch?
And I also found that when using the sklearn wrapper, warning occured saysing that logdir not provided, but shouldn't it be saved in the default path "./log"?

**Comment by brendenpetersen** [comment]
Thanks for the suggestion. This will be coming in a future update!
