### ISSUE TITLE
ValueError in train.py

### ISSUE THREAD

**Issue by TOP1RM** [brendenpetersen/deep-symbolic-optimization#40]
Hello,

I am using the control task of DSO. I recently reinstall everything and ran an ancient program that used to work with my previous installation. My goal is to find control law for simple chaotic dynamical systems (Dadras, Rössler, Lorenz etc...). I created `gym` environements for them, but now I get this error when launch DSO on the Dadras system (not the Lorenz):

MY COMMAND:
`python -m dso.run ~/Bureau/Scripts/Python/DSO/config/DS.json `

THE OUTPUT:
```
WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.


== EXPERIMENT SETUP START ===========
Task type            : control
Environment          : DS-v0
Starting seed        : 0
Runs                 : 1
== EXPERIMENT SETUP END =============

== TRAINING SEED 0 START ============
/home/remi/deep-symbolic-optimization-master/dso/dso/prior.py:757: RuntimeWarning: divide by zero encountered in log
  self.logit_adjust[tokens] -= np.log(len(tokens))
-- BUILDING PRIOR START -------------
WARNING: Skipping invalid 'RelationalConstraint' with arguments {'targets': [], 'effectors': [], 'relationship': None}. Reason: Prior disabled.
WARNING: Skipping invalid 'RepeatConstraint' with arguments {'tokens': 'const', 'min_': None, 'max_': 3}. Reason: Prior disabled.
WARNING: Skipping invalid 'InverseUnaryConstraint' with arguments {}. Reason: There are no inverse unary Token pairs in the Library.
WARNING: Skipping invalid 'TrigConstraint' with arguments {}. Reason: There are no target Tokens.
WARNING: Skipping invalid 'ConstConstraint' with arguments {}. Reason: Uses Tokens not in the Library.
WARNING: Skipping invalid 'LanguageModelPrior' with arguments {'weight': None}. Reason: Prior disabled.
LengthConstraint: Sequences have minimum length 4.
                  Sequences have maximum length 30.
NoInputsConstraint: Sequences contain at least one input variable Token.
UniformArityPrior: Activated.
SoftLengthPrior: No description available.
-- BUILDING PRIOR END ---------------

WARNING: max_length (256) will be overridden by value from LengthConstraint (30).
-- RUNNING EPOCHS START -------------
/home/remi/anaconda3/envs/DSO_env_6/lib/python3.6/site-packages/numpy/core/fromnumeric.py:3373: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/home/remi/anaconda3/envs/DSO_env_6/lib/python3.6/site-packages/numpy/core/_methods.py:170: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
WOLA []
Traceback (most recent call last):
  File "/home/remi/anaconda3/envs/DSO_env_6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/remi/anaconda3/envs/DSO_env_6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/remi/deep-symbolic-optimization-master/dso/dso/run.py", line 156, in <module>
    main()
  File "/home/remi/anaconda3/envs/DSO_env_6/lib/python3.6/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/remi/anaconda3/envs/DSO_env_6/lib/python3.6/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/remi/anaconda3/envs/DSO_env_6/lib/python3.6/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/remi/anaconda3/envs/DSO_env_6/lib/python3.6/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/remi/deep-symbolic-optimization-master/dso/dso/run.py", line 139, in main
    result, summary_path = train_dso(config)
  File "/home/remi/deep-symbolic-optimization-master/dso/dso/run.py", line 33, in train_dso
    result = model.train()
  File "/home/remi/deep-symbolic-optimization-master/dso/dso/core.py", line 83, in train
    **self.config_training))
  File "/home/remi/deep-symbolic-optimization-master/dso/dso/train.py", line 472, in learn
    p_r_best = programs[np.argmax(r)]
  File "<__array_function__ internals>", line 6, in argmax
  File "/home/remi/anaconda3/envs/DSO_env_6/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 1188, in argmax
    return _wrapfunc(a, 'argmax', axis=axis, out=out)
  File "/home/remi/anaconda3/envs/DSO_env_6/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 58, in _wrapfunc
    return bound(*args, **kwds)
ValueError: attempt to get argmax of an empty sequence
```

As stated by the error message, the problem comes from `train.py` at line 471, where the variable `r` is empty, causing the error. I just started to study the code, but I don't think I will have time to understand everything. Maybe an expert could tell me if that error is normal or not.

I don't get this error when working with another dynamical system (Lorenz system for example). My gym environment is the same for Lorenz and Dadras (apart from its behavior, that is to say the equations  of the dynamical system).

Looking forward to an answer. Thanks and regards!
Rémi

**Comment by brendenpetersen** [comment]
Hi, if you post your config I should be able to help!

**Comment by brendenpetersen** [comment]
Feel free to reopen if you want to engage.

**Comment by IgorK7** [comment]
Hi Brended, I have the same issue. 

Here is my code:

            # Initializing and fitting DSR model  
            dso = None
            import dso          
            modelreg = dso.DeepSymbolicRegressor( {   "experiment": {
                "logdir": None
                        },
                        "task" : {
                        "task_type" : "regression",
                        "metric": "inv_nmse", # "r2_shift"
                        "metric_params": (0,),
                        "function_set" : ["add", "sub", "mul", "div", "exp", "log", "sqrt","const" ] # , 
                    } ,
                        "training" : {     "n_cores_batch" : -1
                            },
                            "prior": {
                            "length": {
                            "min_": 3,
                            "max_": 15,
                            "on": True
                        }}})
                        
            X = df.iloc[:i+years_start][["x1","x2"]].values.copy()
            y = df.iloc[:i+years_start][["y"]].values[:,0].copy()
            modelreg.fit(X, y)


Should I provide anything else like the full code?

It works with a some simulated data bit fails on the real data although from a programming point of view there does not seem to be any difference.
I can also provide sample datasets if needed.

**Comment by IgorK7** [comment]
Here is a full config.json and a sample data file.

{
   "experiment": {
      "logdir": "./log",
      "seed": 0,
      "cmd": "path_to_file/dso/dso/run.py path_to_file/config.json",
      "timestamp": "2023-02-21-115723",
      "task_name": "_Users_name",
      "save_path": "./log/_Users_name"
   },
   "task": {
      "task_type": "regression",
      "dataset": "path_to_data/data/DSR_real_test.csv",
      "function_set": [
         "add",
         "sub",
         "mul",
         "div",
         "exp",
         "log",
         "sqrt",
         "const"
      ],
      "metric": "r2_shift",
      "metric_params": [
         0
      ],
      "extra_metric_test": null,
      "extra_metric_test_params": [],
      "threshold": 1e-12,
      "protected": false,
      "reward_noise": 0.0,
      "reward_noise_type": "y_hat",
      "normalize_variance": false,
      "decision_tree_threshold_set": []
   },
   "training": {
      "n_epochs": null,
      "n_samples": 2000000,
      "batch_size": 500,
      "epsilon": 0.02,
      "baseline": "R_e",
      "alpha": 0.5,
      "b_jumpstart": false,
      "n_cores_batch": -1,
      "complexity": "token",
      "const_optimizer": "scipy",
      "const_params": {},
      "verbose": true,
      "debug": 0,
      "early_stopping": true,
      "hof": 100,
      "use_memory": false,
      "memory_capacity": 1000.0,
      "warm_start": null,
      "memory_threshold": null,
      "save_all_epoch": false,
      "save_summary": false,
      "save_positional_entropy": false,
      "save_pareto_front": false,
      "save_cache": false,
      "save_cache_r_min": 0.9,
      "save_freq": 1,
      "save_token_count": false
   },
   "state_manager": {
      "type": "hierarchical",
      "observe_action": false,
      "observe_parent": true,
      "observe_sibling": true,
      "observe_dangling": false,
      "embedding": false,
      "embedding_size": 8
   },
   "controller": {
      "max_length": 256,
      "cell": "lstm",
      "num_layers": 1,
      "num_units": 32,
      "initializer": "zeros",
      "learning_rate": 0.0025,
      "optimizer": "adam",
      "entropy_weight": 0.03,
      "entropy_gamma": 0.7,
      "pqt": true,
      "pqt_k": 10,
      "pqt_batch_size": 1,
      "pqt_weight": 200.0,
      "pqt_use_pg": false,
      "summary": false
   },
   "gp_meld": {
      "run_gp_meld": true,
      "verbose": false,
      "generations": 20,
      "p_crossover": 0.5,
      "p_mutate": 0.5,
      "tournament_size": 5,
      "train_n": 50,
      "mutate_tree_max": 3
   },
   "prior": {
      "count_constraints": false,
      "relational": {
         "targets": [],
         "effectors": [],
         "relationship": null,
         "on": false
      },
      "length": {
         "min_": 3,
         "max_": 10,
         "on": true
      },
      "repeat": {
         "tokens": "const",
         "min_": null,
         "max_": 10,
         "on": true
      },
      "inverse": {
         "on": true
      },
      "trig": {
         "on": true
      },
      "const": {
         "on": true
      },
      "no_inputs": {
         "on": true
      },
      "uniform_arity": {
         "on": false
      },
      "soft_length": {
         "loc": 10,
         "scale": 5,
         "on": true
      },
      "language_model": {
         "weight": null,
         "on": false
      }
   },
   "postprocess": {
[DSR_real_test.csv](https://github.com/brendenpetersen/deep-symbolic-optimization/files/10793506/DSR_real_test.csv)

      "show_count": 5,
      "save_plots": true
   }
}
