### ISSUE TITLE
About customized task

### ISSUE THREAD

**Issue by dragonbra** [brendenpetersen/deep-symbolic-optimization#43]
Hi, I am new to the field of SR and have read your latest paper and am very interested in trying to see if it will work using the SR approach on my own data and task.

I currently think my task is very different from the regression task, so I think I should use the control(not sure what it means) or customized task in DSO. 
My goal is to construct a new expression in the original dataset and evaluate this expression and get a score. Ultimately, I would like to reconstruct the best expression by using SR, by "best" I mean the expression that scores the highest in my own evaluation process.

I'm curious if I can do this by doing a control/customized task in the config? If so, could you have a rough example to show?

**Comment by brendenpetersen** [comment]
Hey there,

I believe you want a custom task. In DSO, a `Task` is largely defined by a search space and a reward function. Both can be arbitrarily/custom designed. For symbolic regression (`regression` task), the search space is the space of mathematical expressions, and the reward function is fitness of that expression to a dataset. For the `control` task, the search space is the same, but the reward function is how well that expression performs when instantiated as a policy in an RL environment.

It sounds like you want to define another `Task` with that same search space (expressions) but a different reward function.

Can't say much else without knowing more, but take a look at the custom example we have and how to configure it. Basically, you'll want to mimic part of the `regression`/`control` task (namely, inherit from `dso.task.HierarchicalTask` and have a `dso.library.Library` consisting of mathematical operators... the combination of these two essentially gives you the expression search space).

Thanks,
Brenden
