### ISSUE TITLE
Evaluation taking much longer than the running epochs

### ISSUE THREAD

**Issue by robvasistha** [brendenpetersen/deep-symbolic-optimization#44]
I've adapted this incredible repo to my custom environment and eventually managed to get it to train. It does take a very long time per epoch even with 10 dedicated cores due to the complexity of the environment.

For the sake of curiosity, I reduced the epochs down to 10  so that I could see what happens once the running phase is over.
The 10 epochs under my environment took approximately 32 minutes.

From train.py I saw that epochs run until nevals is larger than n_samples which is effectively the total epoch time to my understanding.

![image](https://user-images.githubusercontent.com/78962360/184363940-926c3738-2747-4593-ac11-a6acdf106b60.png)
![image](https://user-images.githubusercontent.com/78962360/184364026-7ecb1130-852d-40ae-9ec7-ab5b8302a08a.png)

Looking into the functions following that they should not have much complexity and therefore I would expect the evaluation time to take about the same if not slightly more than the running epochs time. Unfortunately, it is taking much much longer than that and this is still all that I see:
![image](https://user-images.githubusercontent.com/78962360/184363391-b3a88d8b-0a2f-48ca-a489-87ddb2932a9c.png)

Have I done something wrong or is this a bug?
below I will put my config file:
![image](https://user-images.githubusercontent.com/78962360/184363603-c3bcca97-5f8a-40e7-8c94-a629cc27a616.png)

**Comment by robvasistha** [comment]
I did some further debugging on this adding print statements to see at what point the evaluation halts (see image below) and it appears to have some sort of a problem at the results_add line below:
`results_add = logger.save_results(positional_entropy, top_samples_per_batch, r_history, pool, epoch, nevals)`
![image](https://user-images.githubusercontent.com/78962360/184495499-4ae827d1-7f40-4c4f-b3d7-5fdc697b6e00.png)
![image](https://user-images.githubusercontent.com/78962360/184495511-981f233b-5d41-4aea-9d77-ec267a225a9e.png)

**Comment by brendenpetersen** [comment]
See the [template config](https://github.com/brendenpetersen/deep-symbolic-optimization/blob/master/dso/dso/config/config_control.json) for the `control` task.

During training, each sampled expression is used as a policy in the environment for `n_episodes_train` episodes.

During eval, each tested expression is used `n_episodes_test` episodes, which is 100x longer by default, since looks like you didn't change this parameter in your config.

For debugging purposes, I'd just set both `n_episodes_train` and `n_episodes_test` to `1`.

**Comment by brendenpetersen** [comment]
Regarding the prints, you might want to add `flush=True` to be certain that it's not passing more of your DEBUG points. Or use an actual breakpoint or something more robust than printouts.

**Comment by robvasistha** [comment]
Ah I see. 
You are right I missed out on that within my config. 
It does seem to reach further now that I have set it to `1` for both.
Thanks.
