### ISSUE TITLE
Feature : Custom cost function

### ISSUE THREAD

**Issue by arita37** [brendenpetersen/deep-symbolic-optimization#45]
Hello,

Just wondering, how we can use custom cost function ?

```
def mycost(formuale_str)  : 


   cost = myfun( eval(formulae_str)  ,....)

    return cost
```

For many problems, cost is very customized.

**Comment by brendenpetersen** [comment]
You can create your own custom `Task`, which could be an entirely different search space and/or reward function.

In your case, if you want to keep the search space (assuming mathematical expressions based on your snippet above) then it's probably easiest to subclass the `RegressionTask` and overwrite `reward_function`. Or just change `reward_function` locally if you don't care about upstream changes.

**Comment by brendenpetersen** [comment]
#43 also relevant

**Comment by arita37** [comment]
Thanks.

Is it possible to have reference of 
a  very mininal example,
to have the correct class methods
and how to evaluate the math expression:

Does eval(expr) require ?

Thx
