### ISSUE TITLE
How to access the hall of fame?

### ISSUE THREAD

**Issue by soerenab** [brendenpetersen/deep-symbolic-optimization#46]
Hi,

Thanks a lot for this great package and its documentation. I have a question regarding the hall of fame: I am using the `DeepSymbolicRegressor` and after fitting, I am accessing the best program with `model.program_`. This works well! 
Now I am wondering: In [config_common.json](https://github.com/brendenpetersen/deep-symbolic-optimization/blob/master/dso/dso/config/config_common.json) I found the hall of fame parameter `hof`, which (if I understand correctly) defines the number of "best programs" to keep. Is it possible to access these programs after fitting (instead of getting just the single best one as I am doing currently), and if so how would I do this?

Thanks a lot!

**Comment by brendenpetersen** [comment]
Thank you for your interest! You are correct: the "hall of fame" is a record of the top `hof` programs ever seen during training, as measured by `r`.

It sounds like you are using the sklearn regressor interface. This is intended to be a bare-bones interface that does not expose the hall of fame. If you instead run via CLI (i.e. using `python -m dso.run path_to_config.json`), then the hall of fame will be saved to file (ending with `_hof.csv`).

In a future update, the hall of fame will be updated each step during training, not just at the end of training (i.e. after calling `model.fit`), and will be able to be more easily accessible programmatically (e.g. via `model.hof`), as opposed to just with post-`fit` file I/O.

Hope this helps!
