### ISSUE TITLE
How to implement binary power function?

### ISSUE THREAD

**Issue by soerenab** [brendenpetersen/deep-symbolic-optimization#47]
Hi,

Thanks for creating this awesome package! I would like to add a binary power function to represent terms such as `x**1.54` , `x**x` or `(sin(x))**x` etc. I found the function definitions in [function.py](https://github.com/brendenpetersen/deep-symbolic-optimization/blob/master/dso/dso/functions.py#L38:L42) to currently only implement particular powers, e.g. x^2, x^3, x^4. Is it possible to add a "generic" power operator and if so, how would I do that? I am guessing something similar to
` Token(np.power, "pow", arity=2, complexity=??)` but what does the `complexity `parameter represent and what value should I set it to?

Thanks a lot for you help!

**Comment by brendenpetersen** [comment]
Yes, you can easily implement a binary power function like the one above.

`complexity` can be whatever you want and it really isn't used much except as a secondary objective when viewing the Pareto front, e.g. to examine complexity vs reward tradeoffs.

**Comment by soerenab** [comment]
Great, thanks a lot for your help!
