### ISSUE TITLE
multiprocessing error for：“LunarLander_multiobject.json”

### ISSUE THREAD

**Issue by 1176358062** [brendenpetersen/deep-symbolic-optimization#49]
This codebase is really cool. 
However, I got a multithreading error when using the LunarLander_multiobject.json configuration file:

Traceback (most recent call last):
  File "/home/l/miniconda3/envs/dso/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/l/miniconda3/envs/dso/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/l/deep-symbolic-optimization/dso/dso/run.py", line 156, in <module>
    main()
  File "/home/l/miniconda3/envs/dso/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/l/miniconda3/envs/dso/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/l/miniconda3/envs/dso/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/l/miniconda3/envs/dso/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/l/deep-symbolic-optimization/dso/dso/run.py", line 139, in main
    result, summary_path = train_dso(config)
  File "/home/l/deep-symbolic-optimization/dso/dso/run.py", line 33, in train_dso
    result = model.train()
  File "/home/l/deep-symbolic-optimization/dso/dso/core.py", line 83, in train
    **self.config_training))
  File "/home/l/deep-symbolic-optimization/dso/dso/train.py", line 276, in learn
    pool_p_dict = { p.str : p for p in pool.map(work, programs_to_optimize) }   
  File "/home/l/miniconda3/envs/dso/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/l/miniconda3/envs/dso/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
multiprocessing.pool.MaybeEncodingError: Error sending result: '[div,log,add,exp,sub,cos,div,log,div,add,x1,x3,x2,x4,x5,sin,x4,x5,add,cos,log,mul,mul,add,sub,log,mul,exp,1.0,exp,mul,div,x1,add,x7,x1,x6,x6,x8,5.0,1.0,5.0, exp,add,add,mul,sub,sub,x6,div,x2,cos,sub,5.0,x7,0.1,x1,0.1,5.0,exp,sub,sub,add,div,x6,cos,log,x5,exp,5.0,5.0,mul,mul,mul,mul,x6,1.0,x4,x1,x2, cos,exp,exp,mul,x3,div,exp,sub,div,mul,sub,sub,sub,sub,log,x8,exp,x3,x5,0.1,1.0,0.1,x5,1.0,x2,sub,div,div,exp,mul,mul,sub,log,add,cos,x8,exp,add,exp,x8,0.1,x1,5.0,x8,5.0,1.0,1.0, div,x1,mul,mul,cos,log,x8,x5,sub,x5,sin,exp,div,log,log,x7,x7,sub,sub,x3,log,1.0,exp,exp,div,add,div,cos,add,add,x6,1.0,x3,1.0,5.0,1.0, mul,sin,x6,cos,exp,sub,0.1,sub,add,sub,x5,x6,mul,x5,x6,0.1,cos,log,sub,log,1.0,sub,add,log,x1,div,x6,x2,mul,1.0,add,x2,x7, log,mul,mul,mul,log,div,mul,exp,sub,5.0,cos,log,x7,5.0,cos,x8,x6,x7,x4,mul,add,5.0,mul,x3,sub,log,mul,5.0,x2,exp,exp,x8,mul,0.1,x5, sub,x5,cos,log,log,1.0,cos,mul,x5,log,log,mul,exp,exp,0.1,add,exp,exp,1.0,sub,x7,0.1, sub,x1,cos,div,x4,log,div,5.0,add,1.0,mul,x2,exp,div,0.1,0.1,cos,sub,mul,mul,sub,sub,mul,x4,div,1.0,x7,div,5.0,add,x1,mul,add,x4,x3,x1,x2,x4,x5,x4, add,x5,cos,div,mul,log,mul,div,mul,x1,exp,div,x8,exp,sub,mul,1.0,x7,x5,x8,0.1,x8,x5,mul,cos,log,log,div,log,add,exp,sub,1.0,sub,div,sub,1.0,0.1,x1,x1,x6,0.1,x7, add,1.0,sin,sub,x4,log,sub,exp,add,exp,div,log,log,x1,sub,x8,5.0,x3,x6,sub,mul,5.0,x5,div,mul,cos,x8,log,0.1,x8, div,mul,x8,x2,mul,div,log,add,add,div,log,div,cos,x8,add,mul,x8,x6,x2,x8,x3,x1,x6,1.0,sin,mul,1.0,exp,div,1.0,add,div,div,mul,sub,log,log,add,x6,mul,x4,x4,x5,1.0,x5,5.0,x1, add,x6,add,exp,1.0,sin,log,log,x3,cos,sub,add,x6,log,x6,sub,log,sub,add,x7,0.1,sub,exp,x1,x7,5.0, mul,add,sub,mul,x1,cos,log,x2,exp,exp,add,5.0,sub,sin,x8,x5,x8,0.1,log,log,cos,div,mul,log,sub,5.0,sub,exp,x2,add,exp,x3,sub,add,x1,5.0,1.0,0.1,0.1, add,exp,0.1,mul,log,div,x5,x6,div,0.1,x5,exp,add,cos,x4,log,log,add,sin,div,add,sub,x4,sub,add,x1,x6,0.1,x2,x1,x8, sub,add,cos,x2,cos,div,sub,x4,0.1,add,log,mul,exp,div,5.0,1.0,x4,x3,x2,div,x8,sub,x1,mul,x2,exp,1.0, log,sin,exp,add,x4,add,exp,mul,sub,x1,sub,exp,div,x6,x8,exp,x8,1.0,x6,add,mul,x2,cos,div,exp,x7,exp,x2,sin,x4, mul,div,add,div,cos,x2,sin,exp,x4,mul,add,div,5.0,exp,div,x7,x5,x6,x7,x4,x8,div,cos,x4,div,exp,sin,x3,mul,sub,1.0,log,add,log,cos,exp,x7,x8,x8, mul,cos,x6,add,add,div,sub,mul,sub,sin,x3,exp,cos,div,mul,x8,x6,1.0,x6,x7,0.1,x6,x3,log,log,mul,div,x4,cos,x6,x3, add,x1,sub,sub,1.0,sin,add,log,sub,div,exp,1.0,x5,x1,x5,x4,log,add,sub,0.1,div,mul,x1,x3,5.0,cos,sub,mul,x7,div,x7,exp,x8,x7, div,x1,div,x3,exp,sub,log,add,log,x8,exp,add,5.0,x6,exp,x7,exp,cos,sub,exp,sub,x7,x1,log,div,sub,div,add,mul,5.0,x1,0.1,x5,x5,0.1, log,mul,sin,5.0,exp,sub,sin,mul,x5,exp,x4,div,cos,x6,x1,log,div,cos,sub,sub,sub,x5,mul,div,5.0,exp,div,mul,exp,x6,0.1,x3,x5,x4,x8,x5, log,cos,sub,sub,sub,sub,add,x7,x7,add,div,log,div,5.0,1.0,x7,5.0,x7,x6,x1,div,div,x4,mul,div,cos,0.1,x7,x7,div,0.1,mul,mul,x3,cos,x4,x7, mul,1.0,log,log,log,sin,mul,x5,exp,div,0.1,x4,div,sub,add,exp,div,x4,log,x3,div,log,1.0,x6,log,cos,x8,exp,1.0, exp,sin,exp,add,mul,x3,0.1,div,mul,x6,exp,x3,1.0,exp,sub,x5,exp,sub,div,x2,div,x5,x1,cos,x6, sub,log,x2,sin,mul,sub,x1,add,div,div,sub,1.0,5.0,div,log,5.0,x4,x5,1.0,x5,exp,cos,log,sub,x6,add,add,x7,sub,x7,div,x1,x3,add,x2,0.1]'. Reason: 'TypeError("'NoneType' object is not iterable")'

I changed the pool.map to a for loop and it worked successfully, however it was very slow.
How to configure the environment to run the configuration file LunarLander_multiobject.json that optimizes all dimensions at the same time?

**Comment by brendenpetersen** [comment]
Hi, unfortunately our `multiobject` parts of the code are not very well tested because it's a pretty narrow use case for us. I think the issue is over in `program.py::Program.__getstate__` and `program.py::Program.__setstate__`. These define how `multiprocessing` passes `Program` objects back and forth, and apparently this was not done correctly for the `multiobject=True` case.

So, I would simply comments out the two functions `Program.__getstate__` and `Program.__setstate__`. They are not necessary for using `multiprocessing`, and they only give a very small amount of speedup for `multiobject=False`. Actually, in our current internal version of the code (which we hope to update to Github soon!) we removed these two function since they've been problematic. Let us know if this works!

**Comment by 1176358062** [comment]
> 嗨，不幸的是，我们的`multiobject`部分代码没有经过很好的测试，因为这对我们来说是一个非常狭窄的用例。我认为这个问题已经结束`program.py::Program.__getstate__`了`program.py::Program.__setstate__`。这些定义了如何来回`multiprocessing`传递对象，显然在这种情况下没有正确完成。`Program``multiobject=True`
> 
> 所以，我会简单地注释掉这两个函数`Program.__getstate__`和`Program.__setstate__`。它们不是 using 所必需的`multiprocessing`，并且它们只为 . 提供非常少量的加速`multiobject=False`。实际上，在我们当前的代码内部版本（我们希望尽快更新到 Github！）中，我们删除了这两个函数，因为它们存在问题。让我们知道这是否有效！

Thanks, that works for me！
