### ISSUE TITLE
Install on MAC OS

### ISSUE THREAD

**Issue by kpflugho** [brendenpetersen/deep-symbolic-optimization#50]
To whom it may concern,

I have tried several versions (using venv) of Python on OSX to install DSO and all have failed on pip install -e ./dso

3.11.0 & 3.9.13 result in SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.

Tried several items like no cache; pip install wheel, .. others suggested going to an older version of python as shown below

3.8.10 results in ERROR: Could not find a version that satisfies the requirement tensorflow==1.14 

Any help or direction would be appreciated.

Thanks,

Kurt

*** Try following instructions to install dos on Mac using python 3.11.0 ***

Obtaining file:///Users//opt/venv6/dso
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [872 lines of output]
      /Users/kpflugho/opt/venv6/lib/python3.11/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      WARNING: The wheel package is not available.
        error: subprocess-exited-with-error
      
        × Building wheel for numpy (pyproject.toml) did not run successfully.

*** Try following instructions to install dos on Mac using older python 3.9.13 same error ***

(venv5) (base) KPFLUGHO-ML:venv5 kpflugho$ pip install -e ./dso
Obtaining file:///Users/kpflugho/opt/venv5/dso
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [659 lines of output]
      /Users/kpflugho/opt/venv5/venv5/lib/python3.9/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      WARNING: The wheel package is not available.
        error: subprocess-exited-with-error
      
        × Building wheel for numpy (pyproject.toml) did not run successfully.
        │ exit code: 1
        ╰─> [619 lines of output]
            Running from numpy source directory.
            /private/var/folders/f0/xv023w992bjc9yl2ddz_hfr409kf8g/T/pip-wheel-kdbctj66/numpy_724f3c3b1f85491b9f623ec3c6cb0fb0/tools/cythonize.py:73: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.

*** try an older version of python 3.8.10 different error ***

ERROR: Could not find a version that satisfies the requirement tensorflow==1.14 (from dso) (from versions: 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.4.4, 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.6.0rc0, 2.6.0rc1, 2.6.0rc2, 2.6.0, 2.6.1, 2.6.2, 2.6.3, 2.6.4, 2.6.5, 2.7.0rc0, 2.7.0rc1, 2.7.0, 2.7.1, 2.7.2, 2.7.3, 2.7.4, 2.8.0rc0, 2.8.0rc1, 2.8.0, 2.8.1, 2.8.2, 2.8.3, 2.9.0rc0, 2.9.0rc1, 2.9.0rc2, 2.9.0, 2.9.1, 2.9.2, 2.10.0rc0, 2.10.0rc1, 2.10.0rc2, 2.10.0rc3, 2.10.0, 2.11.0rc0, 2.11.0rc1, 2.11.0rc2)
ERROR: No matching distribution found for tensorflow==1.14

**Comment by brendenpetersen** [comment]
Unfortunately DSO is only supported up to python3.7 because tensorflow1.x is not supported beyond this.

**Comment by kpflugho** [comment]
Thanks
