### ISSUE TITLE
Questions and possible errors.

### ISSUE THREAD

**Issue by TOP1RM** [brendenpetersen/deep-symbolic-optimization#57]
Hello,

I am a student and intend to use DSO in my work as I find the concept interesting. I am studying the code, and today I have some problems understanding some lines of code in `program.py`:

1) a `tostring` method is used twice, and I don't find where it is defined, I also don't think it is a python built-in function.

2) in `from_str_tokens` in the part where a list of str|float is converted into a list of tokens we have those lines:
```
for s in str_tokens:
    if s in Program.library.names:
        t = Program.library.names.index(s.lower())
    elif U.is_float(s):
        assert "const" not in str_tokens, "Currently blablabla..."
        t = Program.library.const_token
        constants.append(float(s))
    else:
        raise ValueError("Did not blablabla...")
    traversal.append(t)
traversal = np.array(traversal, dtype=np.int32)
```
Say we have no `PlaceholderConstant` in the library. Then according to `library.py`, `Program.library.const_token` should be equal to `None`. Say we have a float in `str_tokens`. Then we go to the `elif` part. There is no assertion error since there is no `PlaceholderConstant` in the library and thus no `"const"` in the list attribute `Program.library.names`. So `t` is set to `None` and is added to `traversal`. This should, as I understand it, raise this error:
```
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```
in the last line of code (the one converting `traversal` into a numpy array of integers).

3) in `set_constants`, it is written `assert U.is_float, "Input blablabla..."`, but I believe it should be: `assert U.is_float(const), "Input blablabla..."`.

Anyway, even if the things I pointed are errors indeed, it should not be a problem for me as I should only use `HardcodedConstant`. But as I intend to use your work, I better understand the code in depth.

Looking forward to your reply,
Respectfully, TOP1RM

**Comment by brendenpetersen** [comment]
1. In `program.py` we call `tokens.tostring()` a few times, where `tokens` is an `np.ndarray` with `dtype=np.int32`. This is part of the NumPy API: https://numpy.org/doc/stable/reference/generated/numpy.ndarray.tostring.html.

2. It is correct that `Program.library.const_token` is `None` when you have `HardcodedConstant` and no `PlaceholderConstant`. However, if you have a `HardcodedConstant` like 1.23 in your `Library`, you will not hit the `elif` you quoted because the name of the `HardcodedConstant` is "1.23", so the first `if` will be `True`.

3. Yes, it should be `assert U.is_float(const)`.

**Comment by TOP1RM** [comment]
Ok thanks for your responses (here and by email !). I just realized that I figured it out months ago for the `tostring` but I forgot. For the second question, I understand your answer, but then I don't see in what case you will have a float and hit the `elif`. But that is not a problem, as it is a case I will not encounter I believe.

I close this issue, but may reopen it whenever I have other questions !
Thanks again !

**Comment by brendenpetersen** [comment]
You'd hit the `elif` when using a `PlaceholderConstant` because the string will be something like "4.56" (not `"const"`), so it adds a `PlaceholderConstant` to `traversal`.

E.g., `str_tokens = ["add","4.56","x1"]`, where the `Library` has a `PlaceholderConstant` but not `HardcodedConstant`.

**Comment by TOP1RM** [comment]
TOP1RM is coming back

Hello again, tell me if I should keep my remarks/questions for myself or gather them in order to avoid spamming your repository ! Else I may reopen this issue whenever I can't understand a line I will need (as I said before, I am studying the code, but will only work on the parts that I need).

Today, I think there might be an error in `subroutines.py` in the function `jit_check_constraint_violation_descendant_with_target_tokens`. Just below is the code sample I am suspicious about:

```
if a_in_b(action, effector_tokens, T):
    # Does action match a target token?
    descendant = True
    dangling = 1
elif a_in_b(action, target_tokens, T):
    if descendant:
        return True
```
I believe having well understood the mechanics of this function, but as I understand it, it should be something like that:

```
if a_in_b(action, effector_tokens, E):
    # Does action match an effector token?
    descendant = True
    dangling = 1
elif a_in_b(action, target_tokens, T):
    # Does action match a target token?
    if descendant:
        return True
```
And `E` would be equal to `effector_tokens.shape[0]`.

Please accept my apologies if I am wrong.
Best regards, TOP1RM

**Comment by brendenpetersen** [comment]
I'm happy to have you pick out the details for us! I think you are correct above. However, it would be much better to actually show code examples where it's providing the wrong result, instead of relying on us re-interpreting the DSO logic :)

Also, we are happy to accept pull requests for this sort of thing! I think you know exactly the changes to be made :)
