### ISSUE TITLE
Got error installing dso

### ISSUE THREAD

**Issue by junluodigitcompass** [brendenpetersen/deep-symbolic-optimization#58]
Tried to install dso, but got the following error:
What happened?
I downloaded the code file and in the root folder execute the following

pip install -e ./dso[all]

(I am using python 3.9 on windows)

ERROR: Could not find a version that satisfies the requirement tensorflow==1.14 (from dso[all]) (from versions: 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.6.0rc0, 2.6.0rc1, 2.6.0rc2, 2.6.0, 2.6.1, 2.6.2, 2.6.3, 2.6.4, 2.6.5, 2.7.0rc0, 2.7.0rc1, 2.7.0, 2.7.1, 2.7.2, 2.7.3, 2.7.4, 2.8.0rc0, 2.8.0rc1, 2.8.0, 2.8.1, 2.8.2, 2.8.3, 2.8.4, 2.9.0rc0, 2.9.0rc1, 2.9.0rc2, 2.9.0, 2.9.1, 2.9.2, 2.9.3, 2.10.0rc0, 2.10.0rc1, 2.10.0rc2, 2.10.0rc3, 2.10.0, 2.10.1, 2.11.0rc0, 2.11.0rc1, 2.11.0rc2, 2.11.0, 2.11.1, 2.12.0rc0, 2.12.0rc1)
ERROR: No matching distribution found for tensorflow==1.14

It would be appreciated very much for any hints/guidance.
Best,

**Comment by ed0001tt** [comment]
reverting to python 3.7 seems to solve the issue

**Comment by derrynknife** [comment]
3.7 worked for me as well.

**Comment by brendenpetersen** [comment]
Yes, we don't support Python3.9. We will after our PyTorch reimplementation.

**Comment by junluodigitcompass** [comment]
Thanks for all replies.
Finally, it was installed in python 3.7.
with several points worth of mentioning

- one may need to install swig: pip install swig
- it requires tensorflow==1.4, but some python interpreter may use version 2 of tensorflow installed somewhere. For my case, I have to manually delete tensorflow folders in AppData\Roaming\Python\Python37\site-packages
 then install tensorflow: pip install tensorflow==1.4

Thank the team for making the tool dso. Very helpful.
Hope we can see versions of dso for higher version of python, like 3.8 or 3.9.
