### ISSUE TITLE
Set range constraints for const optimization

### ISSUE THREAD

**Issue by ed0001tt** [brendenpetersen/deep-symbolic-optimization#59]
Is it possible to set range constraints for "function_set" that includes "const"? E.g. magnitude of const must greater than 1.

**Comment by brendenpetersen** [comment]
This should be straightforward with the current code by changing your constant optimizer config. The default is:

```json
{
   "training": {
      "const_optimizer" : "scipy",
      "const_params" : {
         "method" : "L-BFGS-B",
         "options" : {
            "gtol" : 1e-3
         }
      }
   }
}
```

The `const_params` dictionary will be passed as `**kwargs` to `scipy.minimzie` (see `program.py#L353` and `const.py#L72`). So any config supported by `scipy.minimize` will be supported by DSO.

So, see `scipy.minimize` docs: https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.minimize.html.

You can set the `bounds` argument there.
