### ISSUE TITLE
About constant term and coefficient

### ISSUE THREAD

**Issue by YuanYuan98** [brendenpetersen/deep-symbolic-optimization#65]
Hi,

After trying this method to discover some physical laws (such as the gravity law), I notice that it fails to deal with constant terms and coefficient terms. Could you please provide ideas to solve this problem? 

Thanks!

**Comment by brendenpetersen** [comment]
Hi, sorry for the delay. DSO on the `regression` tasks finds constant values either using BFGS optimizer (`const` token) or analytically (using the `poly` token). I suggest trying those tokens in your `function_set`.
