### ISSUE TITLE
# AttributeError: 'NoneType' object has no attribute 'execute'

### ISSUE THREAD

**Issue by AILWQ** [brendenpetersen/deep-symbolic-optimization#67]
Dear Petersen,
when I run the skearn interface on my data set, I get the following error:
```
...
File "/home/wangyingli/liwenqiang/uDSR/dso/dso/program.py", line 452, in r
    return self.task.reward_function(self)
  File "/home/wangyingli/liwenqiang/uDSR/dso/dso/task/regression/regression.py", line 197, in reward_function
    y_hat = p.execute(self.X_train)
  File "/home/wangyingli/liwenqiang/uDSR/dso/dso/program.py", line 272, in execute
    result, self.invalid, self.error_node, self.error_type = Program.execute_function(self.traversal, X)
  File "/home/wangyingli/liwenqiang/uDSR/dso/dso/program.py", line 436, in unsafe_execute
    y = execute_function(traversal, X)
  File "/home/wangyingli/liwenqiang/uDSR/dso/dso/execute.py", line 73, in cython_execute
    return cyfunc.execute(X, len(traversal), traversal, is_input_var)
AttributeError: 'NoneType' object has no attribute 'execute'
```
It looks like there is a problem calculating the value of the function corresponding to X, what should I do about it?

Looking forward to your reply, thank you!

**Comment by AILWQ** [comment]
Running the instance program given in the readme also reports the same error, so it shouldn't be a problem with the data set, maybe `cyfunc`.

**Comment by mtrautner** [comment]
I also have this same issue and believe it comes from cyfunc. Running in a virtual environment with the developer version of python did not fix the problem either.

**Comment by brendenpetersen** [comment]
It looks like `cyfunc` is `None`. If `cyfunc` is `None`, then the Cython component of DSO did not install properly. This should be okay though, as DSO is supposed to fall back to the non-Cython implementation of `execute` in this case. However, it looks like this fallback is not working properly.

In `dso/dso/program.py`, we have:
```
# Check if cython_execute can be imported; if not, fall back to python_execute
try:
    from dso.execute import cython_execute
    execute_function = cython_execute
```

I think this should be replaced with:
```
# Check if cython_execute can be imported; if not, fall back to python_execute
try:
    from dso import cyfunc
    from dso.execute import cython_execute
    execute_function = cython_execute
```

Can you see if this fix works?

**Comment by AILWQ** [comment]
> 

Thank you for your reply! Your suggestion solved this problem. Prior to this, I tried using `python_execute(traversal, X)` directly in `dso/dso/execute.py` that also worked.

**Comment by brendenpetersen** [comment]
Awesome! Glad it worked :)
