### ISSUE TITLE
Summing neg log p

### ISSUE THREAD

**Issue by DYSIM** [brendenpetersen/deep-symbolic-optimization#68]
in the function rnn policy -> make_neglogp_and_entropy, you calculate the neglogp for every timestep action sampled, and sum them up to get the neglogp for the sequence. 

Will this not cause the model to prefer shorter sequences? since with shorter sequences the sum will naturally be less. Should we use average instead?

Thank you

**Comment by brendenpetersen** [comment]
> Will this not cause the model to prefer shorter sequences?

Yes. This is true of almost all generative models--that shorter sequences tend to be preferred (higher likelihood) than longer sequences.

> Should we use average instead?

This is a much harder question. I'd say try it out and see what works better!! For symbolic tasks, we are typically interested in parsimony, so it might be helpful to prefer shorter sequences anyway. But not sure there's a "correct answer" here.
