### ISSUE TITLE
Deap fitness objective

### ISSUE THREAD

**Issue by DYSIM** [brendenpetersen/deep-symbolic-optimization#73]
Is there a reason why in Deap the fitness objective is to minimize

`creator.create("FitnessMin", base.Fitness, weights=(-1.0,))`

and the reward is set as -p.r , when is already possible to set FitnessMax from the start like

`creator.create("FitnessMax", base.Fitness, weights=(1.0,))`

which lets the reward be used as it is, without negating.

Thanks!

**Comment by brendenpetersen** [comment]
Nope! That would probably be cleaner. I’d do a parity test and if it passes them replace it as you suggest.  Don’t think I knew about FitnessMax at the time.
