### ISSUE TITLE
Methods for Running DSO 

### ISSUE THREAD

**Issue by AmosJoseph** [brendenpetersen/deep-symbolic-optimization#76]
Hi, thanks for your nice deep-symbolic-optimization. There are two methods running DSO :
Method 1: Running DSO via command-line interface 
Method 2: Running DSO via Python interface

I notice there is another method as it is written:
Sklearn interface
The regression task supports an additional [sklearn-like regressor interface] to make it easy to try out deep symbolic regression on your own data:

Is Sklearn interface  for Running DSO as effective and efficient as Method 1 and 2?

Best regards!

**Comment by brendenpetersen** [comment]
Great question! The Sklearn interface is little more than a thin wrapper for the DeepSymbolicOptimizer object, of course tied to the particular task of symbolic regression.

It’s intended for simpler use or for workflows that can quickly plug-and-play with an Sklearn interface, like the SRBench pipeline which we used to benchmark DSO and win the GECCO competition.

**Comment by AmosJoseph** [comment]
So it's better to use Method 1 and 2 other than the Sklearn interface as it's tied to the particular task of symbolic regression?

**Comment by brendenpetersen** [comment]
Oh, you’d have to use the Python interface to use the sklearn regressor.

**Comment by brendenpetersen** [comment]
Basically I’d say only use sklearn if your regression pipeline needs an sklearn object.
