### ISSUE TITLE
Different Learned Equation with Different Numpy Array Shape

### ISSUE THREAD

**Issue by E-Urzua** [brendenpetersen/deep-symbolic-optimization#79]
Over the past week and a half I have been exploring some use cases of the DSO library with some research that I am doing and have noticed some odd/unexpected behavior through the explorative examples I have come up with. The odd/unexpected behavior that I wanted to ask about is how, when using the sklearn interface, the learned equation from a DSO run with the same config file training points **X** , and test/fit points **y** differs when **y** is  defined as a one dimensional Numpy array - i.e Numpy array shape given as (N,) where  N is the number of points - versus when  when **y** is  defined as a two dimensional one column Numpy array - i.e  Numpy array shape given as (N,1).  To demonstrate what I am saying, when running the below python code 
```python
import numpy as np
from dso import DeepSymbolicRegressor
def main():
    np.random.seed(2)
    num_pnts = 50
    a, b = -2, 2    # used to change the random points from [0, 1) to [a, b)
    X = b*np.random.random((num_pnts,1))+a
    y = X[:,0:1]
    # y =X[:,0]
    config_file = "TestConfig.json"
    model = DeepSymbolicRegressor(config_file)
    model.fit(X, y) 
    print(model.program_.pretty())
if __name__ == '__main__':
    main()
```
where the TestConfig.json file is the first noted json file below, the resulting learned equation is $\frac{1}{\cos{e}}$ however by just changing the line `y = X[:,0:1]`  to `y = X[:,0]` the learned equation is $x~1$ which is the correct equation. So I wanted to ask if the library authors knew about this or not and in the latter case if the simple fix to this odd/unexpected behavior would be to check that the array ``y`` is defined as a one dimensional array and if not copy and reshape it to be one (for example in the fit function of the DeepSymbolicRegressor class found in the sklean.py file). 

Another thing that I would add to this is that this behavior also results in a run time error being thrown when the function set parameter within the config Json file contains the "poly" argument. Specifically, if the below code is run with second JSON file, 
```python
import numpy as np
from dso import DeepSymbolicRegressor
def main():
    np.random.seed(2)
    num_pnts = 50
    a, b = -2, 2    # used to change the random points from [0, 1) to [a, b)
    X = b*np.random.random((num_pnts,1))+a
    y = X[:,0:1]
    # y =X[:,0]
    config_file = "TestConfig.json"
    model = DeepSymbolicRegressor(config_file)
    model.fit(X, y) 
    print(model.program_.pretty())
if __name__ == '__main__':
    main()
``` 
it results in ValueError with with the whole error message being the following:

> Traceback (most recent call last):
  File "DSOtesting1.py", line 78, in <module>
    main()
  File "DSOtesting1.py", line 66, in main
    model.fit(X, y)
  File "c:\users\urzua\desktop\my shit\uci and sdsu stuff\research_work\pytorchtests\deep-symbolic-optimization-master\dso\dso\task\regression\sklearn.py", line 39, in fit
    train_result = self.train()
  File "c:\users\urzua\desktop\my shit\uci and sdsu stuff\research_work\pytorchtests\deep-symbolic-optimization-master\dso\dso\core.py", line 114, in train
    result = self.train_one_step()
  File "c:\users\urzua\desktop\my shit\uci and sdsu stuff\research_work\pytorchtests\deep-symbolic-optimization-master\dso\dso\core.py", line 95, in train_one_step
    self.trainer.run_one_step(override)
  File "c:\users\urzua\desktop\my shit\uci and sdsu stuff\research_work\pytorchtests\deep-symbolic-optimization-master\dso\dso\train.py", line 291, in run_one_step
    r = np.array([p.r for p in programs])
  File "c:\users\urzua\desktop\my shit\uci and sdsu stuff\research_work\pytorchtests\deep-symbolic-optimization-master\dso\dso\train.py", line 291, in <listcomp>
    r = np.array([p.r for p in programs])
  File "c:\users\urzua\desktop\my shit\uci and sdsu stuff\research_work\pytorchtests\deep-symbolic-optimization-master\dso\dso\utils.py", line 112, in __get__
    value = self.getter(obj)
  File "c:\users\urzua\desktop\my shit\uci and sdsu stuff\research_work\pytorchtests\deep-symbolic-optimization-master\dso\dso\program.py", line 452, in r
    return self.task.reward_function(self)
  File "c:\users\urzua\desktop\my shit\uci and sdsu stuff\research_work\pytorchtests\deep-symbolic-optimization-master\dso\dso\task\regression\regression.py", line 194, in reward_function
    p.traversal[p.poly_pos] = self.poly_optimizer.fit(self.X_train, poly_data_y)
  File "c:\users\urzua\desktop\my shit\uci and sdsu stuff\research_work\pytorchtests\deep-symbolic-optimization-master\dso\dso\task\regression\polyfit.py", line 461, in fit
    return Polynomial(list(compress(pod.all_exponents, mask)), self.regressor.coef_[mask])
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

Having looked a bit into why this problem happens, it appears to have something to do with how the library is determining the coefficients for the polynomial terms as the mask array in line 461 of the polyfit.py file is a three dimensional array and not a 1 dimensional array and so the `list(compress(pod.all_exponents, mask)` bit of the code throws the error. However again when running the above Python code with  ` y =X[:,0]` instead of ` y =X[:,0:1]`, no error is thrown and the correct function is learned $y=x~1$. I though I would also mention this behavior that I notice there since it seems to be related to the first behavior I noticed and was curious about with `y` not being defined as a one dimensional Numpy array. 

I hope that I have given sufficient information to reproduce the behavior that I have noticed and explained it in enough detail but should there be any further bits of information that I need to give and clarify, please let me know and I will get back on that as quickly as I can. 

#### First JSON file
```json
{
    "experiment" : {
        "logdir" : "./log",
        "seed" : 1
    },

    "task" : {
        "task_type" : "regression",
        "function_set" :  ["add", "sub", "mul", "div", "sin", "cos", "exp", "log", "sqrt","n2","n3","n4"],
        "metric" : "inv_nrmse",
        "metric_params" : [1.0],
        "extra_metric_test" : null,
        "extra_metric_test_params" : [],
        "threshold" : 1e-12,     
        "protected" : false,
        "reward_noise" : 0.0,
        "reward_noise_type" : "r",
        "normalize_variance" : false,

         "decision_tree_threshold_set" : [],

         "poly_optimizer_params" : {
            "degree": 2,
            "coef_tol": 1e-6,
            "regressor": "dso_least_squares",
            "regressor_params": {
               "cutoff_p_value": 1.0,
               "n_max_terms": null,
               "coef_tol": 1e-6
            }
        }
    },
    "training" : {
        "n_samples" : 2000000,
        "batch_size" : 2000,

        "epsilon" : 0.05,
        "baseline" : "R_e",

        "alpha" : 0.5,
        "b_jumpstart" : false,

        "n_cores_batch" : 1,

        "complexity" : "token",

        "const_optimizer" : "scipy",
        "const_params" : {
           "method" : "L-BFGS-B",
           "options" : {
              "gtol" : 1e-3
           }
        },
        "verbose" : true,

        "debug" : 0,

        "early_stopping" : true,

        "use_memory" : false,
        "memory_capacity" : 1e3,
        "warm_start" : null,
        "memory_threshold" : null
    },
    "logging" : {
        "save_all_iterations" : false,
        "save_summary" : false,
        "save_positional_entropy" : false,
        "save_pareto_front" : true,
        "save_cache" : false,
        "save_cache_r_min" : 0.9,
        "save_freq" : 1,
        "save_token_count" : false,
        "hof" : 100
    },
    "state_manager": {
        "type" : "hierarchical",
        "observe_action" : false,
        "observe_parent" : true,
        "observe_sibling" : true,
        "observe_dangling" : false,
        "embedding" : false,
        "embedding_size" : 8
    },
    "policy" : {

        "policy_type" : "rnn", 

        "max_length" : 64,

        "cell" : "lstm",
        "num_layers" : 1,
        "num_units" : 32,
        "initializer" : "zeros"
    },
    "policy_optimizer" : {

        "policy_optimizer_type" : "pg", 

        "summary" : false,

        "learning_rate" : 0.001,
        "optimizer" : "adam",

        "entropy_weight" : 0.005,
        "entropy_gamma" : 1.0
    },
    "gp_meld" : {
        "run_gp_meld" : false,
        "verbose" : false,
        "generations" : 20,
        "p_crossover" : 0.5,
        "p_mutate" : 0.5,
        "tournament_size" : 5,
        "train_n" : 50,
        "mutate_tree_max" : 3,
        "parallel_eval" : false
    },


    "prior": {
        "count_constraints" : false,

        "relational" : {
                "targets" : [],
                "effectors" : [],
                "relationship" : null,
                "on" : false
            },

        "length" : {
                "min_" : 1, 
                "max_" : 15,
                "on" : true
            },

        "repeat" : {
                "tokens" : "const",
                "min_" : null,
                "max_" : 3,
                "on" : true 
            },

        "inverse" : {
                "on" : true
            },

        "trig" : {
                "on" : true 
            },

        "const" : {
                "on" : true
            },

        "no_inputs" : {
                "on" : true 
            },

        "uniform_arity" : {
                "on" : true 
            },

        "soft_length" : {
                "loc" : 5,
                "scale" : 2,
                "on" : true 
            },

        "domain_range" : {
                "on" : false
            },

        "language_model" : {
                "weight" : null,
                "on" : false
            },

        "multi_discrete" : {
                "dense" : false,
                "ordered" : false,
                "on" : false
            }
    },
    "postprocess" : {
        "show_count" : 5,
        "save_plots" : true
    }
}
```
#### Second JSON file
```json
{
    "experiment" : {
        "logdir" : "./log",
        "seed" : 1
    },

    "task" : {
        "task_type" : "regression",
        "function_set" :  ["add", "sub", "mul", "div", "sin", "cos", "exp", "log", "sqrt","poly"],
        "metric" : "inv_nrmse",
        "metric_params" : [1.0],
        "extra_metric_test" : null,
        "extra_metric_test_params" : [],
        "threshold" : 1e-12, 
        "protected" : false,
        "reward_noise" : 0.0,
        "reward_noise_type" : "r",
        "normalize_variance" : false,

        "decision_tree_threshold_set" : [],

        "poly_optimizer_params" : {
            "degree": 2,
            "coef_tol": 1e-6,
            "regressor": "dso_least_squares",
            "regressor_params": {
               "cutoff_p_value": 1.0,
               "n_max_terms": null,
               "coef_tol": 1e-6
            }
        }
    },
    "training" : {
        "n_samples" : 2000000,
        "batch_size" : 2000,

        "epsilon" : 0.05,
        "baseline" : "R_e",

        "alpha" : 0.5,
        "b_jumpstart" : false,

        "n_cores_batch" : 1,

        "complexity" : "token",

        "const_optimizer" : "scipy",
        "const_params" : {
           "method" : "L-BFGS-B",
           "options" : {
              "gtol" : 1e-3
           }
        },
        "verbose" : true,

        "debug" : 0,

        "early_stopping" : true,

        "use_memory" : false,
        "memory_capacity" : 1e3,
        "warm_start" : null,
        "memory_threshold" : null
    },
   "logging" : {
        "save_all_iterations" : false,
        "save_summary" : false,
        "save_positional_entropy" : false,
        "save_pareto_front" : true,
        "save_cache" : false,
        "save_cache_r_min" : 0.9,
        "save_freq" : 1,
        "save_token_count" : false,
        "hof" : 100
    },
    "state_manager": {
        "type" : "hierarchical",
        "observe_action" : false,
        "observe_parent" : true,
        "observe_sibling" : true,
        "observe_dangling" : false,
        "embedding" : false,
        "embedding_size" : 8
    },
    "policy" : {

        "policy_type" : "rnn", 

        "max_length" : 64,

        "cell" : "lstm",
        "num_layers" : 1,
        "num_units" : 32,
        "initializer" : "zeros"
    },
    "policy_optimizer" : {

        "policy_optimizer_type" : "pg", 

        "summary" : false,

        "learning_rate" : 0.001,
        "optimizer" : "adam",

        "entropy_weight" : 0.005,
        "entropy_gamma" : 1.0
    },
    "gp_meld" : {
        "run_gp_meld" : false,
        "verbose" : false,
        "generations" : 20,
        "p_crossover" : 0.5,
        "p_mutate" : 0.5,
        "tournament_size" : 5,
        "train_n" : 50,
        "mutate_tree_max" : 3,
        "parallel_eval" : false
    },


    "prior": {
        "count_constraints" : false,

        "relational" : {
                "targets" : [],
                "effectors" : [],
                "relationship" : null,
                "on" : false
            },

        "length" : {
                "min_" : 1,
                "max_" : 15,
                "on" : true 
            },

        "repeat" : {
                "tokens" : "const",
                "min_" : null,
                "max_" : 3,
                "on" : true 
            },

        "inverse" : {
                "on" : true
            },

        "trig" : {
                "on" : true 
            },

        "const" : {
                "on" : true 
            },

        "no_inputs" : {
                "on" : true 
            },

        "uniform_arity" : {
                "on" : true
            },

        "soft_length" : {
                "loc" : 5,
                "scale" : 2,
                "on" : true 
            },

        "domain_range" : {
                "on" : false
            },

        "language_model" : {
                "weight" : null,
                "on" : false
            },

        "multi_discrete" : {
                "dense" : false, 
                "ordered" : false, 
                "on" : false
            }
    },
    "postprocess" : {
        "show_count" : 5,
        "save_plots" : true
    }
}
```

**Comment by brendenpetersen** [comment]
Hi, thank you for the detailed report!

Yes, `y` should always be one-dimensional. If it's 2D (even with a single column, as in your example), the symbolic operators are likely doing something you don't expect.

I agree it would be better to raise a `ValueError` or similar if `y.ndim != 1`. Would be happy to take a PR for this behavior.

**Comment by E-Urzua** [comment]
Hi and thank you very much for the quick response here.

Glad I could be of some help in bringing the behavior with the `poly` token to your attention. On the PR for this behavior, I am do not happen to use GitHub all that often so do not exactly know how to properly issue pull requests and then merger my edits back with the library but I will do my best. I do have one question though, aside from in the fit function of the the DeepSymbolicRegressor class found in the sklean.py file, is there would there be any other place to check that either `y.ndim!=1` or to raise a Value Error? I have only been doing my exploratory examples using the sklearn interface but know that the pair `(X, y)` can be given in the config file through some way and so I assume that checking the number of dimensions of `y` would probably be needed somewhere else as well correct? 

That all being said I will make a pull request, make the edit mentioned about and look for anywhere else that the library may need a similar edit. For any further questions I have on the library I will either make a new issue or email you directly since I have some questions regarding the creation of new function/tokens (derivative related).

**Comment by brendenpetersen** [comment]
The sklearn interface is just a thin wrapper to the DeepSymbolicOptimizer object tied to the regression task. So yes, it would make more sense to do in the base object, or more specifically the RegressionTask.

Might need to be done in 2 places. First checking the training data shape, which can be done in RegressionTask I think.

The second would be for eval. Since the base DSO object doesn’t do prediction, might need to that in the Sklearn interface.

**Comment by E-Urzua** [comment]
Got it and I will take a look into all those places that you mentioned and make the edits I see fit and then after doing some test runs issue the PR. 

Again should I need to get some clarification or ask anything else I will make sure to do so here or through direct email.
