### ISSUE TITLE
Doubts about output

### ISSUE THREAD

**Issue by AmosJoseph** [brendenpetersen/deep-symbolic-optimization#80]
Hi, I have some questions  about output! 

![1688217686230](https://github.com/brendenpetersen/deep-symbolic-optimization/assets/40055065/6779e122-6085-44de-a469-2fe55d955010)
![1688217709473](https://github.com/brendenpetersen/deep-symbolic-optimization/assets/40055065/f3e4fa80-4219-4fa9-9360-7d7874387a31)

seed：0  
r：0.970982  
nmse_test ：0.000893
nmse_test_noiseless ：0.000893    
success ：FALSE    
expression：extremely complex and long!
r square is 0.970982, but why success shows FALSE? What's wrong?

**Comment by brendenpetersen** [comment]
Success is only true when you exactly recover an expression on noiseless data. It doesn’t mean the algorithm failed. Looks like you found a pretty good fit!
