### ISSUE TITLE
training iteration N, current best R : 0.9 

### ISSUE THREAD

**Issue by AmosJoseph** [brendenpetersen/deep-symbolic-optimization#83]
Hi, when current best R is good enough, such as 0.9782 after many training iterations, say 1330, is it possible to stop the code running? 
As there is error, code running is stopped and the final result is not obtained.

Or how to correct the corresponding parameters in config.json when a good fitting is reached?

**Comment by brendenpetersen** [comment]
The `threshold` parameter under `task` config controls the NRMSE at which to stop training. Depending on your reward function (inverse NRMSE is default) you'll have to back calculate the NRMSE value that you want.
